
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_YAS532),y)
obj-y	+=  yamaha532/
endif

ifeq ($(CONFIG_MTK_QMC6983_NEW),y)
obj-y	+=  qmc6983-new/
endif
