
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_MPU6515G),y)
obj-y	+=  mpu6515/
endif

ifeq ($(CONFIG_MTK_LSM6DS0_NEW),y)
obj-y   +=  lsm6ds0-new/
endif
